# Generated by Django 4.1.4 on 2023-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=True, verbose_name="Is Admin"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=False, verbose_name="Is Customer"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deliveryboy",
            field=models.BooleanField(default=False, verbose_name="Is DeliveryBoy"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_restaurantowner",
            field=models.BooleanField(default=True, verbose_name="Is RestaurantOwner"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
