# Generated by Django 4.1.4 on 2023-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
                ("category_pic", models.ImageField(upload_to="img/category_picture/")),
                ("category_status", models.BooleanField(default=False)),
            ],
        ),
    ]
