# Generated by Django 4.1.4 on 2023-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Customer_Phoneno",
            field=models.CharField(max_length=10),
        ),
    ]
