# Generated by Django 4.1.4 on 2023-02-14 18:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="img/order/")),
                ("restaurant_id", models.CharField(max_length=100)),
                ("f_name", models.CharField(default="", max_length=100)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("area", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=10)),
                ("pin_code", models.CharField(max_length=6)),
                ("quantity", models.CharField(max_length=5)),
                ("price", models.IntegerField()),
                ("total", models.CharField(default="", max_length=1000)),
                ("date", models.DateField(default=datetime.datetime.today)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
