# Generated by Django 4.1.4 on 2023-02-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_order_choice",
            field=models.CharField(
                choices=[("Accept", "Accept"), ("Reject", "Reject")],
                default="Accept",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("Going To Restaurant", "Going To Restaurant"),
                    ("Picked Up", "Picked Up"),
                    ("Delivered", "Delivered"),
                ],
                default="Going To Restaurant",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready for pickup"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
