# Generated by Django 4.1.4 on 2023-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_order_delivery_order_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_order_choice",
            field=models.CharField(
                choices=[
                    ("Select", "Select"),
                    ("Accept", "Accept"),
                    ("Reject", "Reject"),
                ],
                default="Select",
                max_length=20,
            ),
        ),
    ]
