# Generated by Django 4.1.4 on 2023-03-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_alter_order_delivery_order_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_total",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
