# Generated by Django 4.1.4 on 2023-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_restaurant_data_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant_data",
            name="Restaurant_Phoneno",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
