# Generated by Django 4.1.4 on 2023-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deliveryboydata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DeliveryBoy_Fullname", models.CharField(max_length=100)),
                ("DeliveryBoy_PhoneNO", models.CharField(max_length=14)),
                ("DeliveryBoy_Email", models.EmailField(max_length=254)),
                ("DeliveryBoy_AdharcardNo", models.CharField(max_length=12)),
                ("DeliveryBoy_DrivingLicenceNo", models.CharField(max_length=15)),
                ("DeliveryBoy_PanCard", models.CharField(max_length=10)),
            ],
        ),
    ]
