# Generated by Django 4.1.4 on 2023-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveryboy", "0002_deliveryboydata_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryboydata",
            name="DeliveryBoy_PhoneNO",
            field=models.CharField(max_length=10),
        ),
    ]
